2021/02/19 10:19:26 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost:8099"
2021/02/19 10:36:23 [error] 27#27: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost:8099, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost:8099"
2021/02/19 10:39:55 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost:8099, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost:8099"
2021/02/19 10:50:39 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost:8099"
2021/02/22 03:28:43 [error] 28#28: *3 connect() failed (113: No route to host) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.7:9000", host: "localhost:8099"
2021/02/22 03:28:51 [error] 28#28: *5 connect() failed (113: No route to host) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.7:9000", host: "localhost:8099"
